CREATE TABLE TSUser
(
    EmpID INT NOT NULL PRIMARY KEY,
    LastName VARCHAR(100),
    FirstName VARCHAR(100)
);

CREATE TABLE TSParam
(
    ParamID INT AUTO_INCREMENT PRIMARY KEY,
    TSDayOfWeek VARCHAR(50),
    TSRange VARCHAR(50),
    TSLunchPeriod VARCHAR(2),
    fk_EmpID INT, 
    FOREIGN KEY (fk_EmpID) REFERENCES TSUser(EmpID)
);
ALTER TABLE TSParam AUTO_INCREMENT = 100;    

CREATE TABLE TSPunches
(
    PunchID INT AUTO_INCREMENT PRIMARY KEY,
    TSEntryDate VARCHAR(10) NOT NULL,
    TSEntryTime VARCHAR(5) NOT NULL,
    fk_EmpID INT NOT NULL, 
    FOREIGN KEY (fk_EmpID) REFERENCES TSUser(EmpID)
);